<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">accessValues</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gUmV0cmlldmUgdGhlIFhtbERhdGEgb3V0cHV0IGZyb20gdGhlIGNvbnZlcnNpb24gc2Vydmlj
ZQ0KSURhdGEgaW5wdXQgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChwaXBlbGluZSwgInht
bERhdGFEb2N1bWVudCIpOw0KDQovLyBPYnRhaW4gYW4gWG1sRGF0YUN1cnNvcg0KWG1sRGF0YUN1
cnNvciB4ZGMgPSBYbWxEYXRhLmdldFhtbERhdGFDdXJzb3IoaW5wdXQpOyANCi8vIFBvc2l0aW9u
IHRvIHRoZSBmaXJzdCBvbmx5IGVsZW1lbnQsICJlbXBsb3llZSINCnhkYy5maXJzdCgpOw0KDQov
LyBSZXRyaWV2ZSBpdHMgdmFsdWUgd2hpY2ggaXMgYW4gZW1wbG95ZWUgRG9jdW1lbnQNCklEYXRh
IGVtcFZhbHVlID0gKElEYXRhKSB4ZGMuZ2V0VmFsdWUoKTsNCi8vIE9idGFpbiBhIGN1cnNvciBv
biB0aGUgZW1wbG95ZWUgRG9jdW1lbnQNClhtbERhdGFDdXJzb3IgeGRjMiA9IFhtbERhdGEuZ2V0
WG1sRGF0YUN1cnNvcihlbXBWYWx1ZSk7DQoNCi8vIFBvc2l0aW9uIHRvIHRoZSB0YWcgIm5hbWUi
DQp4ZGMyLmZpcnN0KG5ldyBYbWxEYXRhRWxlbWVudFRhZygibmFtZSIpKTsNCi8vIFJldHJpZXZl
IHRoZSBTVHJpbmcgdmFsdWUNClN0cmluZyBuYW1lVmFsdWUgPSAoU3RyaW5nKSB4ZGMyLmdldFZh
bHVlKCk7DQoNCi8vIFB1dCB0aGUgcmV0cmlldmVkIG5hbWUgdmFsdWUgaW50byB0aGUgcGlwZWxp
bmUNClZhbHVlc0VtdWxhdG9yLnB1dChwaXBlbGluZSwgInJlc3VsdCIsIG5hbWVWYWx1ZSk7DQov
LyBSZWxlYXNlIHJlc291cmNlcw0KeGRjLmRlc3Ryb3koKTsNCnhkYzIuZGVzdHJveSgpOwkNCgk=
</value>
</Values>
