<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">second</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gUmV0cmlldmUgdGhlIFhtbERhdGEgb3V0cHV0IGZyb20gdGhlIGNvbnZlcnNpb24gc2Vydmlj
ZQ0KSURhdGEgaW5wdXQgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChwaXBlbGluZSwgInht
bERhdGFEb2N1bWVudCIpOw0KDQovLyBjcmVhdGUgdGhlIHdvcmtzcGFjZQ0KWG1sRGF0YVdvcmtz
cGFjZSB3cyA9IFhtbERhdGFXb3Jrc3BhY2UuZ2V0U2VydmVyV29ya3NwYWNlKCk7DQp3cy5zZXRG
b2xkZXIoInhtbGRhdGFzYW1wbGVzLnBhdGgiKTsNCk5TRmllbGQgcmVjID0gd3MuZ2V0V3JhcHBl
cihuZXcgWG1sRGF0YUVsZW1lbnRUYWcoImFscGhhIiwgInNhbXBsZU1hcHMiKSk7DQovLyBhc3Nv
Y2lhdGUgdGhlIFhtbERhdGEgaW5mb3NldCB3aXRoIHRoZSB3cmFwcGVyIGZvciB0aGUgImFscGhh
IiByb290IGVsZW1lbnQNClhtbERhdGFNYXAgbWFwID0gWG1sRGF0YU1hcC5jcmVhdGUoaW5wdXQs
IChOU1JlY29yZCkgcmVjKTsNCg0KLy8gRmV0Y2ggYSB2YWx1ZSB1c2luZyB0aGUgc2NyaXB0IGZv
cm0gb2YgYSBNYXAgUGF0aA0KT2JqZWN0IG8gPSBtYXAuZ2V0VmFsdWUoIntucyBzYW1wbGVNYXBz
fS9uczphbHBoYS9uczp0aHJlZS9uczpjaGFybGllL25zOnF1YXJrIik7DQoJCQ0KLy8gc2F2ZSB0
aGUgcmVzdWx0IHRvIHRoZSBwaXBlbGluZQkJDQpWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUs
ICJhbnN3ZXIiLCBvKTsJCQ0KCQ==</value>
</Values>
