<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">first</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gUmV0cmlldmUgdGhlIFhtbERhdGEgb3V0cHV0IGZyb20gdGhlIGNvbnZlcnNpb24gc2Vydmlj
ZQ0KSURhdGEgaW5wdXQgPSAoSURhdGEpIFZhbHVlc0VtdWxhdG9yLmdldChwaXBlbGluZSwgInht
bERhdGFEb2N1bWVudCIpOw0KLy8gY3JlYXRlIGEgYnVmZmVyIGZvciBjb25zb2xlIG91dHB1dA0K
U3RyaW5nQnVpbGRlciBzYiA9IG5ldyBTdHJpbmdCdWlsZGVyKCk7DQoNCi8vIE9idGFpbiBhbiBY
bWxEYXRhVHJlZUN1cnNvcg0KWG1sRGF0YVRyZWVDdXJzb3IgeGRjID0gWG1sRGF0YS5nZXRYbWxE
YXRhVHJlZUN1cnNvcihpbnB1dCk7DQovLyBQb3NpdGlvbiB0byB0aGUgZmlyc3QgYW5kIG9ubHkg
ZWxlbWVudCwgInJvb3QiDQp4ZGMuZmlyc3QoKTsNCi8vIHBvc2l0aW9uIG9uIHRoZSBmaXJzdCBj
aGlsZA0KeGRjLmZpcnN0Q2hpbGQoKTsNCg0KLy8gaXRlcmF0ZSBvdmVyIGl0ZW1zDQpzYi5hcHBl
bmQoeGRjLmdldFRhZygpLnRvU3RyaW5nKCkgKyAiICIgKyB4ZGMuZ2V0VmFsdWUoKSArICJcbiIp
Ow0Kd2hpbGUoeGRjLm5leHRJdGVtKCkpIA0KCXNiLmFwcGVuZCh4ZGMuZ2V0VGFnKCkudG9TdHJp
bmcoKSArICIgIiArIHhkYy5nZXRWYWx1ZSgpICsgIlxuIik7DQpzYi5hcHBlbmQoIlxuIik7DQoN
Ci8vIHBvc2l0aW9uIG9uIGZpcnN0IG9iamVjdCBhZ2Fpbg0KLy8gaXRlcmF0ZSBhZ2FpbiB1c2lu
ZyB0aGUgWG1sRGF0YUN1cnNvciBtZXRob2RzDQp4ZGMuZmlyc3QoKTsNCnNiLmFwcGVuZCh4ZGMu
Z2V0VGFnKCkudG9TdHJpbmcoKSArICIgIiArIHhkYy5nZXRPYmplY3QoKSArICJcbiIpOw0Kd2hp
bGUoeGRjLm5leHQoKSkgDQoJc2IuYXBwZW5kKHhkYy5nZXRUYWcoKS50b1N0cmluZygpICsgIiAi
ICsgeGRjLmdldE9iamVjdCgpICsgIlxuIik7DQpWYWx1ZXNFbXVsYXRvci5wdXQocGlwZWxpbmUs
ICJjb25zb2xlIiwgc2IudG9TdHJpbmcoKSk7DQoNCi8vIFJlbGVhc2UgcmVzb3VyY2VzDQp4ZGMu
ZGVzdHJveSgpOw0KDQoJ</value>
</Values>
